#!/bin/bash
	
nice -n 1 ./loop1 > /dev/null &
nice -n 1 ./loop2 > /dev/null &
nice -n 0 ./loop3 > /dev/null &

sleep 1m
ps -o pid,state,time,command | grep [l]oop > salida.txt

for i in $(pgrep loop) 
do
	kill $i
done
